nome=input('qual e o teu nome completo?')
nome1=nome.upper()
nome2=nome.lower()
nome3=len(nome)
nome4=nome.split()
print('seu nome em letras maiusculas e {}'.format(nome1))
print('seu nome em letras minusculas e {}'.format(nome2))
print('seu nome tem no total {} de letras'.format(nome3))
print('seu primeiro nome tem ao todo {} letras'.format(len(nome4[0])))