print('========== aluga movel ==========')
d=int(input('quantos dias alugados'))
k=float(input('quantos km andados'))
r1=(d*60)
r2=(k*0.15)
r3=(r2+r1)
print('                       ')
print('o total que vc deve pelo carro e R${}'.format(r3))
print('                       ')
print('=================================')