print('========== FICHA ==========')
nome=input('qual e o seu nome:')
idade=input('qual e a sua idade:')
altura=input('qual e a sua altura:')
print('===========================')
print('seu nome e:',nome)
print('sua idade e:',idade)
print('sua altura e:',altura)
print('===========================')